name: Feature request
description: Suggest a feature to improve Keploy
title: "[feature]: "
labels: [feature]
body:

- type: markdown
  attributes:
    value: |
     - ## If you want to add an issue related to this docs repository then plz add your issue [_at this location_](https://github.com/keploy/keploy/issues) 
     - ## please add a docs <img src="https://i.imgur.com/iFVxQdE.png"> label on your issue.


- type: checkboxes
  attributes:
    label: Have you checked that your issue is unique ?
    options:
    - label: Yes my issue is uniques.
      required: true









