name: Feature request
description: Suggest a feature to improve Keploy
title: "[feature]: "
labels: [feature]
body:


- type: checkboxes
  attributes:
 
   
    options:
    - label: go on https://github.com/keploy/keploy/issues section for creating your issue and don't forget to add docs label on your
     issue so that people could understand that issue is relted with docs repository.
      required: true