name: Feature request
description: Suggest a feature to improve Keploy
title: "[feature]: "
labels: [feature]
body:

- type: markdown
  attributes:
    value: |
     ## If you want to add an issue related to this docs repositiry then plz add your issue [_at this location_](https://github.com/keploy/keploy/issues) and please add a docs      <img src="https://i.imgur.com/UcymfwC.png"> label.


- type: checkboxes
  attributes:
    label: plz visit the link given below for creating issue.
    options:
    - label: go on        section for creating your issue and add doc lable.
      required: true









