name: Feature request
description: Suggest a feature to improve Keploy
title: "[feature]: "
labels: [feature]
body:

- type: markdown
  attributes:
    value: |
     # If you want to add an issue related to this repositiry then plz add your issue in keploy/keploy repository with a docs label, so that people could understand that the issue is related to docs repository.


- type: checkboxes
  attributes:
    label: 
   
    options:
    - label: go on https://github.com/keploy/keploy/issues section for creating your issue.
      required: true