import React, {useEffect, useRef, useState} from "react";
import {Copy, Check, FileText, AlertCircle} from "lucide-react";

/**
 * MarkdownPageActions - "Copy page" / "View as Markdown" links, rendered
 * directly under the page title (mirrors the docs.sarvam.ai / Mintlify
 * pattern: title, then a thin actions row, then a divider, then body).
 * Point at the .md twin generated by docusaurus-plugin-llms at build time.
 */
export default function MarkdownPageActions({mdUrl}) {
  const [copyState, setCopyState] = useState("idle");
  const resetTimeoutRef = useRef(null);

  useEffect(() => {
    return () => clearTimeout(resetTimeoutRef.current);
  }, []);

  if (!mdUrl) return null;

  const handleCopy = async () => {
    clearTimeout(resetTimeoutRef.current);
    setCopyState("copying");
    try {
      const res = await fetch(mdUrl);
      if (!res.ok) throw new Error(`Request failed: ${res.status}`);
      const text = await res.text();
      await navigator.clipboard.writeText(text);
      setCopyState("copied");
    } catch (e) {
      setCopyState("error");
    } finally {
      resetTimeoutRef.current = setTimeout(() => setCopyState("idle"), 2000);
    }
  };

  const copyLabel =
    copyState === "copying"
      ? "Copying…"
      : copyState === "copied"
        ? "Copied"
        : copyState === "error"
          ? "Copy failed"
          : "Copy as Markdown";

  const CopyIcon =
    copyState === "copied" ? Check : copyState === "error" ? AlertCircle : Copy;

  const copyColorClasses =
    copyState === "copied"
      ? "text-green-600 dark:text-green-500"
      : copyState === "error"
        ? "text-red-600 dark:text-red-500"
        : "text-gray-500 dark:text-gray-400";

  const linkBase =
    "inline-flex items-center gap-1 text-[12px] leading-[1.2] py-[0.2rem] px-2 m-0 " +
    "no-underline transition-colors duration-150 hover:text-[#ff914d] " +
    "[&>svg]:shrink-0 [&>svg]:opacity-75";

  return (
    <div className="flex items-center mt-1.5 mb-3 pb-3 border-b border-black/[0.08] dark:border-white/10">
      <button
        type="button"
        className={`${linkBase} pl-0 bg-transparent border-0 cursor-pointer disabled:cursor-default disabled:opacity-70 ${copyColorClasses}`}
        onClick={handleCopy}
        disabled={copyState === "copying"}
      >
        <CopyIcon size={12} strokeWidth={2} aria-hidden="true" />
        {copyLabel}
      </button>
      <a
        className={`${linkBase} border-l border-black/[0.12] dark:border-white/[0.14] text-gray-500 dark:text-gray-400`}
        href={mdUrl}
        target="_blank"
        rel="noopener noreferrer"
      >
        <FileText size={12} strokeWidth={2} aria-hidden="true" />
        View as Markdown
      </a>
    </div>
  );
}
