name: "CLA Assistant"

on:
  issue_comment:
    types:
      - "created"
  pull_request_target:
    types:
      - "opened"
      - "closed"
      - "synchronize"

jobs:
  cla-assistant:
    runs-on: "ubuntu-latest"
    steps:
      - name: "CLA Assistant"
        if: "(github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'"
        uses: "cla-assistant/github-action@v2.1.3-beta"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          PERSONAL_ACCESS_TOKEN: "${{ secrets.PRO_ACCESS_TOKEN }}"
        with:
          remote-organization-name: "keploy"
          remote-repository-name: "docs"
          path-to-signatures: "etc/cla-signatures/signatures.json"
          path-to-document: "https://github.com/keploy/docs/tree/main/.github/CLA.md"
          branch: "cla-signatures"
          allowlist: "keploy-bot,renovate"