name: Check Docusaurus docs with Vale linter

on: [pull_request]

jobs:
  vale:
    name: Vale doc linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      # Set up Vale Action
      - uses: errata-ai/vale-action@v2.1.1
        with:
          # Filter mode can be set to: added, diff_context, file, nofilter
          filter_mode: nofilter
          # Set the reporter to display the output: github-pr-check, github-pr-review, github-check
          reporter: github-pr-check
          # Fails the action if there are errors
          fail_on_error: true
          # Lint the files in the "versioned_docs/version-2.0.0/" directory
          files: 'versioned_docs/version-2.0.0'
          # Specify the Vale version
          version: 3.0.3
        env:
          # GitHub token for authentication, automatically set by GitHub Actions
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
